---
title: "Reproducibility of macrophage-mesenchymal association"
author: "Zhiyuan Hu"
date: "03/02/2020 (last modified: `r Sys.Date()`)"
output: 
  prettydoc::html_pretty:
    theme: architect
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(Biobase)
library(GEOquery)
library(ggpubr)
```

# Summary

This analysis is aimed to verify that the association between macrophage and mesenchymal componants is reproducible in multiple independent datasets.

# Read data

```{r}
path <- "~/OneDrive - Nexus365/Project scRNAseq analysis/A_SmartSeq2/man_analysis2_20180629/R_deconvolution/rds"
cod_esets <- readRDS(paste(path, "/20190213CuratedOvarianData_esets.rds", sep = ""))
tcga_eset <- readRDS(paste(path, "/20181029TCGA_eset.rds", sep = ""))
aocs_eset <- readRDS(paste(path, "/20181029_tothill_eset.rds", sep = ""))

sigmat <- read.csv("../data/new_list 20200119Gene_Panelv2_combined.csv", as.is = T)
```


```{r}
decon <- readRDS("../../../Project scRNAseq analysis/A_SmartSeq2/scFT-paper_rds/20200203CuratedOvarianData_deconvolution_res.rds")
```

list("E.MTAB.386", "GSE13876", "GSE26193",
              "GSE26712", "GSE32062.GPL6480",
              "GSE49997", "GSE51088")

# Normalisation

```{r distribution_sequencing_depth_codeset1}
hist(colSums(cod_esets[[1]]@assayData$exprs))
```




# Correlation test

```{r}
library ("rstan")
```


```{r}
cor.test(tcga_eset@assayData$exprs["CD163",], tcga_eset@assayData$exprs["SPARC",])
```

```{r}
cor.test(tcga_eset@assayData$exprs["CD163",], tcga_eset@assayData$exprs["GAPDH",])
```

```{r}
cor.test(aocs_eset@assayData$exprs["CD163",], aocs_eset@assayData$exprs["SPARC",])
```


```{r}
cor.test(aocs_eset@assayData$exprs["CD163",], aocs_eset@assayData$exprs["GAPDH",])
```

```{r}
cor.test(cod_esets[[1]]@assayData$exprs["CD163",], cod_esets[[1]]@assayData$exprs["SPARC",])
```

```{r}
cor.test(cod_esets[[1]]@assayData$exprs["CD163",], cod_esets[[1]]@assayData$exprs["GAPDH",])
``` 
 
```{r}
cor.test(cod_esets[[2]]@assayData$exprs["CD163",], cod_esets[[2]]@assayData$exprs["SPARC",])
```

```{r}
cor.test(cod_esets[[2]]@assayData$exprs["CD163",], cod_esets[[2]]@assayData$exprs["GAPDH",])
```

```{r}
cod_esets[[3]] <- cod_esets[[3]][,cod_esets[[3]]$histological_type == "ser"]
cor.test(cod_esets[[3]]@assayData$exprs["CD163",cod_esets[[3]]$histological_type == "ser"], cod_esets[[3]]@assayData$exprs["SPARC",cod_esets[[3]]$histological_type == "ser"])
```

```{r}
cor.test(cod_esets[[3]]@assayData$exprs["CD163",cod_esets[[3]]$histological_type == "ser"], cod_esets[[3]]@assayData$exprs["GAPDH",cod_esets[[3]]$histological_type == "ser"])
```

```{r}
cod_esets[[4]] <- cod_esets[[4]][,cod_esets[[4]]$sample_type =="tumor"]
cor.test(cod_esets[[4]]@assayData$exprs["CD163", cod_esets[[4]]$sample_type =="tumor"], cod_esets[[4]]@assayData$exprs["SPARC", cod_esets[[4]]$sample_type =="tumor"])
```

```{r}
cor.test(cod_esets[[4]]@assayData$exprs["CD163", cod_esets[[4]]$sample_type =="tumor"], cod_esets[[4]]@assayData$exprs["GAPDH", cod_esets[[4]]$sample_type =="tumor"])
```

```{r}
cor.test(cod_esets[[5]]@assayData$exprs["CD163",], cod_esets[[5]]@assayData$exprs["SPARC",])
```


```{r}
cod_esets[[6]] <- cod_esets[[6]][,cod_esets[[6]]$histological_type=="ser"]
cor.test(cod_esets[[6]]@assayData$exprs["CD163",cod_esets[[6]]$histological_type=="ser"], cod_esets[[6]]@assayData$exprs["SPARC",cod_esets[[6]]$histological_type=="ser"])
```

```{r}
cor.test(cod_esets[[6]]@assayData$exprs["CD163",cod_esets[[6]]$histological_type=="ser"], cod_esets[[6]]@assayData$exprs["GAPDH",cod_esets[[6]]$histological_type=="ser"])
```

SPARC: A_23_P7642
GAPDH: A_23_P13897
CD163: A_23_P33723

```{r}
gset <- getGEO("GSE51088", GSEMatrix =TRUE, getGPL=FALSE)
gset <- gset[[1]]
df <- gset@assayData$exprs[c("A_23_P7642","A_23_P13897","A_23_P33723"),]
rownames(df) <- c("SPARC","GAPDH","CD163")
df <- df[,which(cod_esets[[7]]$histological_type == "ser")]
df <- t(na.omit(t(df)))
```

```{r}
cor.test(df["SPARC",], df["CD163",])
```



# make tidy data

```{r}
aocs_eset <- aocs_eset[,aocs_eset$histological.subtype == "Ser"]
```

```{r}
tmp <- log1p(tcga_eset@assayData$exprs[c("CD163","SPARC"),])
tmp <- cbind(tmp,aocs_eset@assayData$exprs[c("CD163","SPARC"),])
tmp <- cbind(tmp,cod_esets[[1]]@assayData$exprs[c("CD163","SPARC"),])
tmp <- cbind(tmp,cod_esets[[2]]@assayData$exprs[c("CD163","SPARC"),])
tmp <- cbind(tmp,cod_esets[[3]]@assayData$exprs[c("CD163","SPARC"),])
tmp <- cbind(tmp,cod_esets[[4]]@assayData$exprs[c("CD163","SPARC"),])
tmp <- cbind(tmp,cod_esets[[5]]@assayData$exprs[c("CD163","SPARC"),])
tmp <- cbind(tmp,cod_esets[[6]]@assayData$exprs[c("CD163","SPARC"),])
tmp <- cbind(tmp,df[c("CD163","SPARC"),])
tmp <- t(tmp)
```


```{r}
id <- c(rep(1, ncol(tcga_eset)),
         rep(2, ncol(aocs_eset)),
         rep(3, ncol(cod_esets[[1]])),
         rep(4, ncol(cod_esets[[2]])),
         rep(5, ncol(cod_esets[[3]])),
         rep(6, ncol(cod_esets[[4]])),
         rep(7, ncol(cod_esets[[5]])),
         rep(8, ncol(cod_esets[[6]])),
         rep(9, ncol(df))
         )
id <- id[!(is.na(tmp[,1]) | is.na(tmp[,2]))]
tmp <- tmp[!(is.na(tmp[,1]) | is.na(tmp[,2])),]
N <- length(id)
J <- 9
X <- tmp[,"SPARC"]
y <- tmp[,"CD163"]
```


# stan - simulation

```{r}
set.seed(12345)
m_hier <- stan(file="linearregression.stan",data=list(N=N,J=J,id=id,X=X,y=y))
```

```{r}
print(m_hier)
```

```{r}
#extract the MCMC samples
mcmc_hier <- extract(m_hier)
str(mcmc_hier)
```



```{r}
# pdf("plots/SPARC_CD163_mcmc_hier_gamma_20200508.pdf")
plot(density(as.numeric(mcmc_hier$gamma)))
# dev.off()
```


# scatter plot


```{r}
df_plot <- data.frame(tmp, id)
df_id <- data.frame(id = 1:9,
                    name = c("TCGA","AOCS","E.MTAB.386","GSE13876","GSE26193","GSE26712","GSE34062.GPL6480","GSE49997","GSE51088")
)
df_plot$name <- df_id$name[match(df_plot$id, df_id$id)]
df_plot$name <- factor(df_plot$name, levels = df_id$name)
ggplot(df_plot, aes(x = SPARC, y = CD163)) +
  geom_smooth(method="lm", alpha = 0.5) + 
    geom_point(size=1, pch = 21, col = "grey40", fill = alpha("grey60", 0.5)) + 
    facet_wrap(~name, scales = "free")  + theme_classic2() + xlab("Expression levels of SPARC") + 
    ylab("Expression levels of CD163") 
    
# ggsave("plots/SPARC_CD163_9datasets_scatter_with_lm20200523.pdf", width = 6, height = 5)
```


## Technical

```{r}
sessionInfo()
```

